postgres:
  build: ./build/postgres/
  ports:
    - "5432:5432"
  volumes:
    - /var/lib/docker/speak_data/postgres:/var/lib/postgresql

gophergalasubs:
  build: .
  env_file: .env
  ports:
    - "8080:8080"
  volumes:
    - ./static:/go/src/github.com/awsmsrc/gophergalasubs/static
  links:
    - postgres

